site_name: Eris
site_url: https://eris.laarryy.dev

nav:
  - Home: index.md
  - Setup: setup.md
  - Features: features.md
  - Commands:
      - General Commands: general-commands.md
      - Punishment Commands: punishment-commands.md
      - Raid Commands: raid-commands.md
      - Search Commands: search-commands.md
      - Setting Commands: setting-commands.md
  - AutoMod: automod.md
  - About: about.md
  - Privacy Policy: privacy-policy.md
  - Terms of Use: terms-of-use.md

# Theme
theme:
  name: 'material'
  language: 'en'
  palette:
    - scheme: 'default'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: 'deep purple'
      accent: 'indigo'
    - scheme: 'slate'
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: 'deep purple'
      accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  icon:
    admonition:
      note: fontawesome/solid/sticky-note
      abstract: fontawesome/solid/book
      info: fontawesome/solid/info-circle
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/question-circle
      warning: fontawesome/solid/exclamation-triangle
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

# Site Info
# repo_url: https://github.com/ErisMB
# repo_name: Eris on GitHub
site_description: Documentation for the Discord moderation bot Eris
site_author: Laarryy
copyright: Copyright &copy; ErisMB

# Plugins
plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
